### ISSUE TITLE
Add local sources to Fontface declarations

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-styles#4]
We need to add a setting to fonts (local) which can be a slice or a string.

```yaml
tnd_styles:  
  fonts:
    - family: Play
      style: normal
      weight: 400
      file: fonts/files/play-v11-latin-regular
      local: 
        - Play Regular
        - Play-Regular
```
