### ISSUE TITLE
Add sensible default local declaration

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-styles#5]
With the following local:

```
tnd_styles:
  fonts:
    - family: Play
      file: fonts/files/play-v11-latin-regular
      local: Play Regular
```

We should automatically create two local src:
```
local('Play regular'), local('Play-Regular')
```
